### ISSUE TITLE
US-SysML-to-B-demonstration Prio: 410

### ISSUE THREAD

**Issue by mahlmann** [openETCS/product-backlog#75]
As a modeller I want to know the migration path from SysML to B so that I can implement the model with open tools.

**Comment by MERCEmentre** [comment]
I made a demonstrator working with a (modified) SysML diagram of openETCS (Marielle's Level diagram): https://github.com/openETCS/modeling/tree/master/demo/SysML2B

A Java file needs to be edited to match local configuration:
https://github.com/openETCS/modeling/blob/master/demo/SysML2B/LevelLunaModelGenerator/src/levellunamodelgenerator/Application.java#L23

Then, "Run as..."->"Eclipse Application" on the LevelLunaModelGenerator project.

Currently, one needs to add Acceleo into openETCS tool-chain to make it work (https://github.com/openETCS/toolchain/issues/502).

**Comment by MERCEmentre** [comment]
Status update: Acceleo and the model has been included in official tool-chain. I need to check that everything works as expected.

**Comment by MERCEmentre** [comment]
Tested on v1.0.1-final. It does not work: "java.io.IOException: '/org/openetcs/sysml2b/transformation/common/main/m_MainSysMLTransform.emtl' not found".

Indeed, *.emtl files (Acceleo compiled filed) are missing into plugins\org.openetcs.sysml2b.transformation_1.0.1.201512092102.jar file. *.mtl (Acceleo source files) are correctly put in the jar file.

We won't fix because it was last release so you can close the issue.

**Comment by jastram** [comment]
Closed, as discussed.
